site_name: Xentis' Steel Compendium
site_url: https://steelcompendium.io

copyright: The Draw Steel Compendium is an independent product published under the DRAW STEEL Creator License and is not affiliated with MCDM Productions, LLC. DRAW STEEL Â© 2025 MCDM Productions, LLC.

theme:
   name: 'material'
   palette:
      scheme: slate
      primary: black
      accent: blue
   logo: Media/favicon.ico
   favicon: Media/favicon.ico

# Extensions
markdown_extensions:
   - footnotes
   -  pymdownx.arithmatex:
         generic: true
   -  pymdownx.tasklist:
         custom_checkbox: true
   - def_list
   - pymdownx.critic
   - pymdownx.caret
   - pymdownx.keys
   - pymdownx.mark
   - pymdownx.tilde
   -  pymdownx.superfences:
         custom_fences:
            -  name: mermaid
               class: mermaid
               format: !!python/name:pymdownx.superfences.fence_code_format
   -  toc:
         permalink: true
         toc_depth: 1-8

plugins:
   - search
   - roamlinks

extras:
   analytics:
      provider: google
      property: G-PMF9SHHXNY

extra_css:
   - stylesheets/extra.css
   - stylesheets/custom_font.css

extra_javascript:
   - javascripts/mathjax.js
   - https://polyfill.io/v3/polyfill.min.js?features=es6
   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
   - https://unpkg.com/mermaid/dist/mermaid.min.js
   - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
   - javascripts/tablesort.js
